import 'package:greenap/domain/models/my_challenge.dart';
import 'package:greenap/domain/enums/challenge.dart';

final List<MyChallengeModel> dummyMyChallenges = [
  MyChallengeModel(
    id: 1,
    challengeId: 8,
    title: '텀블러 사용하기',
    category: '자원절약',
    totalDays: 30,
    elapsedDays: 10,
    progress: 33,
    iceCount: 0,
    isCerficatedInToday: ChallengeCertificated.SUCESSED,
    status: ChallengeStatus.running,
    certificationDataList: [
      {'date': '2025-04-01', 'is_certificated': 'true'},
      {'date': '2025-04-02', 'is_certificated': 'true'},
      {'date': '2025-04-03', 'is_certificated': 'true'},
      {'date': '2025-04-04', 'is_certificated': 'true'},
      {'date': '2025-04-05', 'is_certificated': 'false'},
      {'date': '2025-04-06', 'is_certificated': 'true'},
      {'date': '2025-04-07', 'is_certificated': 'true'},
      {'date': '2025-04-08', 'is_certificated': 'true'},
      {'date': '2025-04-09', 'is_certificated': 'true'},
      {'date': '2025-04-10', 'is_certificated': 'true'},
    ],
  ),
  MyChallengeModel(
    id: 2,
    challengeId: 13,
    title: '채식 식단 실천하기',
    category: '친환경',
    totalDays: 14,
    elapsedDays: 14,
    progress: 100,
    iceCount: 1,
    isCerficatedInToday: ChallengeCertificated.FAILED,
    status: ChallengeStatus.completed,
    certificationDataList: [
      {'date': '2025-03-28', 'is_certificated': 'true'},
      {'date': '2025-03-29', 'is_certificated': 'false'},
      {'date': '2025-03-30', 'is_certificated': 'false'},
      {'date': '2025-03-31', 'is_certificated': 'false'},
      {'date': '2025-04-01', 'is_certificated': 'ice'},
      {'date': '2025-04-02', 'is_certificated': 'ice'},
      {'date': '2025-04-03', 'is_certificated': 'true'},
      {'date': '2025-04-04', 'is_certificated': 'ice'},
      {'date': '2025-04-05', 'is_certificated': 'ice'},
      {'date': '2025-04-06', 'is_certificated': 'true'},
      {'date': '2025-04-07', 'is_certificated': 'true'},
      {'date': '2025-04-08', 'is_certificated': 'true'},
      {'date': '2025-04-09', 'is_certificated': 'true'},
      {'date': '2025-04-10', 'is_certificated': 'true'},
    ],
  ),
  MyChallengeModel(
    id: 3,
    challengeId: 18,
    title: '대중교통 이용하기',
    category: '교통절감',
    totalDays: 7,
    elapsedDays: 2,
    progress: 28,
    iceCount: 1,
    isCerficatedInToday: ChallengeCertificated.FAILED,
    status: ChallengeStatus.running,
    certificationDataList: [
      {'date': '2025-04-01', 'is_certificated': 'ice'},
      {'date': '2025-04-02', 'is_certificated': 'ice'},
    ],
  ),
];
