spring:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  sql:
    init:
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql
      mode: always


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(CWgkr/ek7FmtMfVCDTYiXKo56J+fGmfiQiqI8RnUKg+shRNRE0mk9qeGIVvifj7Vz57mAffzUaU4GGjarYZp16CPJYOwPALVxQcomOQaD38vT8prF84vtg==)
            client-secret: ENC(wJvlJnBXkjQRa6A8e/wYMjlhwh46J3x6lV5Tz9UOKNh7W039BRl62To+W0+Hill5)
            scope:
              - email
              - profile

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:storage/credentials.json
        project-id : ENC(HbMzdTcgXp1XGuBK82QEAImUvfRQjdgu)
        bucket: ENC(mK2lM6LFaxvy3UcM8qIKlAf69MhR3bYfX455cqx6i2K8R4JpGuUL2Q==)

android-key:
  client-android-id: ENC(EYtumXjQCQJuyFZkp1CVNfr0pzVrECohYLBpnpDzTlhm1iB0gLbiQx2xULIbYPCNNAPyLIM4QZtuJ2y9aJdl73plpyq17EEfhKr9hySTD1pUAghV4CENoQ==)

certification-server:
  url: ENC(Xnj5O9qpb+DUt2FguNbMIMXCB3lSMsAOnYTOQ8MRR7uMDFe0R3su3p9tVBwlWAYXYZDYJeb5BgV2lU14ZWhssGkykeVts+ioBTXtle6ga8s=)

report-server:
  url: ENC(l5GHgDH/bebNDUs5fOUknnLYXsXd8CCVCo+f4t0vPOdU4ahV8+TKIwnYouB9Fxtzm1noFDj0IrLuN8Ib1oUfav4nDdcEM7HFtv1rIagiqXnNqzV8fKWafw==)

encourage-message-server:
  url: ENC(zQqQI20tvLC+cE9MMFguOTrrHrxy87MMVALZ7jWPdJzlF7DoKzPUf89GOXfNCcdvmGCZIEzwbzCc/4lbAorBnah0bvbqvuGEhr8dsIs/W1s=)

# Jasypt
jasypt:
  encryptor:
    password: ${JASYPT_KEY}

jwt:
  secret: ENC(NjIWxjCj+OYhKxPp5rdLnA5m3XGrhU/iN9x198OteRtHPuhVLgNoHn/3qsSVcFu4JgYmJ4/b43m5lGNgIRHPrvpl318zik0D5RQv236Ni8Fe8Ue10YagCHWUo5mWrgkZdKRQ/2Tbs62UftkKfklM07EOZPI1LuPxPiWRxC1CT4sf5+7wJY5i4piDWWlPhyjs)
  access-token-validity-in-milli-seconds: 3600000
  refresh-token-validity-in-milli-seconds: 86400000
logging:
  level:
    root: debug

springdoc:
  swagger-ui:
    operations-sorter: method
    path: /
    groups-order: desc
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    groups:
      enabled: true
